// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hifksggqkimdfqlhcosx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpZmtzZ2dxa2ltZGZxbGhjb3N4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MTcwOTQsImV4cCI6MjA2OTI5MzA5NH0.pbj6wzYanCE2PyfkAXhpbp9iCQMLcIWqGxely9LAHJo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});